const ELEMENTS_MARGIN_TOP = 100;
const ELEMENT_HEIGHT = 80;
const ELEMENT_MARGIN_BOTTOM = 16;
const ELEMENTS_MARGIN_BOTTOM = 40;

export {
  ELEMENTS_MARGIN_TOP,
  ELEMENT_HEIGHT,
  ELEMENT_MARGIN_BOTTOM,
  ELEMENTS_MARGIN_BOTTOM,
};
