const HEADIN_MARGIN_TOP = 40;
const HEADIN_MARGIN_BOTTOM = 20;
const TAB_HEIGHT = 56;
const TAB_MARGIN_BOTTOM = 40;
const TYPE_BLOCK_PADDING_BOTTOM = 40;

export {
  HEADIN_MARGIN_TOP,
  HEADIN_MARGIN_BOTTOM,
  TAB_HEIGHT,
  TAB_MARGIN_BOTTOM,
  TYPE_BLOCK_PADDING_BOTTOM,
};
